server:
  port: 8088

spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.146:3306/test_www_db
    username: test_user
    password: test_user

logging:
  level:
    cn.linuxhub.springboot: debug
